version: '3'
services:
  backend:
    image: encuestas-backend
    environment:
      MAX_MEMORY_JVM: 1536
      START_MEMORY_JVM: 1536
    ports:
      - "8080:8080"
    networks:
      - encuestas
    depends_on:
      - mysql
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2048M

  mysql:
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: arqdb
      MYSQL_USER: arq
      MYSQL_PASSWORD: arq
    ports:
      - "3306:3306"
    networks:
      - encuestas

networks:
  encuestas:
